/* tslint:disable */
/* eslint-disable */
/**
 * Demo API
 *  This is a demo app
 *
 * The version of the OpenAPI document:  v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

