/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    Bottom: typeof import('./src/components/bottom.vue')['default']
    Business: typeof import('./src/components/Business.vue')['default']
    BusinessBottom: typeof import('./src/components/BusinessBottom.vue')['default']
    BusinessHeader: typeof import('./src/components/BusinessHeader.vue')['default']
    BusinessInfoCom: typeof import('./src/components/BusinessInfoCom.vue')['default']
    BusinessList: typeof import('./src/components/BusinessListCom.vue')['default']
    BusinessListCom: typeof import('./src/components/BusinessListCom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    FoodType: typeof import('./src/components/FoodType.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeTop: typeof import('./src/components/HomeTop.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IGgAirplane: typeof import('~icons/gg/airplane')['default']
    ISvgSpinners6DotsRotate: typeof import('~icons/svg-spinners/6-dots-rotate')['default']
    PaymantCom: typeof import('./src/components/PaymentCom.vue')['default']
    PaymentCom: typeof import('./src/components/PaymentCom.vue')['default']
    Recommend: typeof import('./src/components/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuperMember: typeof import('./src/components/SuperMember.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
